name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.5.1
  chat_ui_kit: ^1.3.0
  just_audio: ^0.9.18
#  flutter_video_info: ^1.2.0 #retrieve video metadata
#  video_thumbnail: ^0.4.3 #get a thumbnail from a file
#  implicitly_animated_reorderable_list: ^0.4.0
#  intl: ^0.17.0
#  functional_widget_annotation: ^0.9.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


  assets:
    - assets/avatars/
    - assets/other/

